version: '3.3'
services:
  qywechat-api:
    container_name: qywechat-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: 'v6ole/qywechat-api:latest'
    ports:
      - '8800:80'
    volumes:
      - ./rootfs/etc/nginx/http.d:/etc/nginx/http.d
      - ./rootfs/app/web:/app/web
    environment:
      - TZ=Asia/Shanghai 