name: Docker readme update

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  job:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/qywechat-api
          short-description: 企业微信API代理服务
          readme-filepath: ./README.md